### ISSUE TITLE
Strange implementation of getStreetName

### ISSUE THREAD

**Issue by tshemsedinov** [diia-open-source/be-pkg-utils#10]
It would be easier to write such code in place instead of remembering we have it and check 

https://github.com/diia-open-source/be-pkg-utils/blob/e969374fb769e59ab6bbdb709caeba0199e14a8c/src/applicationUtils.ts#L259-L265

Also here we check street and return empty string instead of throwing errors.

Why do we need trim() here?

**Comment by tshemsedinov** [comment]
> Thank you for being so passionate!

Thank you, GPT!

**Comment by kant2002** [comment]
> the quality of information is not always good enough

В мене питання, а чому для кейсу коли тип вулиці не вказаний, обрізання рядка не відбуваєтся. я так розумію що проблеми із якістю будуть і у цьому випадку.

**Comment by DiiaOpenSource** [comment]
Вітаю, @kant2002 !  Це залежить від джерела даних, в деяких випадках відсутній тип вулиці (провулок, проспект, тощо) тому, в результаті парсінгу, вулиця може опинитися на позиції де ми очікуємо тип. Загалом, це все побудовано на підставі досвіду, отриманого під час роботи з різними джерелами даних.
Дякуэмо Вам за вашу небайдужість!

**Comment by creotiv** [comment]
Ok, why then heuristic method not used to return same street format as much as possible. You have tons of data of different string types and names, its very simple to build algorithm that will get same format out of all this data. Instead we have strange function that concatenates two strings
