### ISSUE TITLE
You will never need this util

### ISSUE THREAD

**Issue by tshemsedinov** [diia-open-source/be-pkg-utils#20]
https://github.com/diia-open-source/be-pkg-utils/blob/e969374fb769e59ab6bbdb709caeba0199e14a8c/src/guards.ts#L69-L74

Let's optimize: 
```js
   static isSettledError(value: PromiseSettledResult<unknown>): value is PromiseRejectedResult {
        return value.status === 'rejected'
    }
```

So you can simply use inplace expression Instead you can use in place just `isSettledError`: 

```js
value.status === 'rejected'
```

**Comment by doichev-kostia** [comment]
The key value of this util is in `value is PromiseRejectedResult`. This is needed for TypeScript in `Array.filter` method.

<img width="1221" alt="Screenshot 2024-03-21 at 11 25 47" src="https://github.com/diia-open-source/be-pkg-utils/assets/72884674/f2b63e48-b312-4989-bffd-b85da50d0434">
<img width="1040" alt="Screenshot 2024-03-21 at 11 26 16" src="https://github.com/diia-open-source/be-pkg-utils/assets/72884674/01b35938-6981-4dce-b137-417d94e1de98">

**Comment by FowiFlowi** [comment]
@doichev-kostia exactly!
